#!/bin/bash

echo "🚀 HF Spaces Deployment Process"
echo "================================"
echo ""
echo "Step 1: Create HF Space"
echo "   Go to: https://huggingface.co/new-space"
echo "   Name: physical-AI-Humanoid-Book"
echo "   SDK: Docker"
echo "   Hardware: CPU (free)"
echo ""
echo "Step 2: Clone the created space"
echo "   git clone https://huggingface.co/spaces/Awais68/physical-AI-Humanoid-Book hf-space"
echo ""
echo "Step 3: Copy files and push"
echo "   cd hf-space"
echo "   rm -rf .git"
echo "   cp -r ~/physical-ai/* ."
echo "   git init"
echo "   git add ."
echo '   git commit -m "Initial deployment"'
echo "   git remote add origin https://huggingface.co/spaces/Awais68/physical-AI-Humanoid-Book"
echo "   git push -u origin main"
echo ""
echo "Step 4: Add secrets in HF Space Settings"
echo "   OPENAI_API_KEY"
echo "   GEMINI_API_KEY"
echo "   COHERE_API_KEY"
echo ""
echo "🎉 Your space will be live at:"
echo "   https://huggingface.co/spaces/Awais68/physical-AI-Humanoid-Book"
