#!/bin/sh
'''exec' '/media/awais/6372445e-8fda-42fa-9034-61babd7dafd1/150 GB DATA TRANSFER/hackathon series/physical-AI-Homanoid-Book-main/backend/.venv/bin/python' "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import sys
from huggingface_hub.cli.hf import main
if __name__ == "__main__":
    if sys.argv[0].endswith("-script.pyw"):
        sys.argv[0] = sys.argv[0][:-11]
    elif sys.argv[0].endswith(".exe"):
        sys.argv[0] = sys.argv[0][:-4]
    sys.exit(main())
